version: '3.5'
networks:
  aw-net: {}
services:
  der-alex:
    build:
      context: ./
      dockerfile: Dockerfile
    environment: 
      NUXT_HOST: 0
      HOST: 0
    container_name: der-alex
    command: node index.mjs
    volumes:
      - ./:/usr/src/app
    ports:
      - 1337:3000
    networks:
      - aw-net
